server.port=${APP_PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.redis.url=${REDIS_URL}
paytrail.paystack.secret-key=${PAYSTACK_SECRET_KEY}
paytrail.super-api-key=${SUPER_API_KEY}
paytrail.scheduler.batch-size=${SCHEDULER_BATCH_SIZE:50}
paytrail.scheduler.interval-ms=${SCHEDULER_INTERVAL_MS:10000}
